"""Added field is_pretty to user

Revision ID: 7d6902545413
Revises: c93ad4028363
Create Date: 2026-06-17 21:57:39.692437

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6902545413'
down_revision: Union[str, Sequence[str], None] = 'c93ad4028363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pretty', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pretty')
    # ### end Alembic commands ###
